version: '3.8'
services:
  front:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '8080:8080'
    volumes:
      - /app/node_modules
      - ./app:/app
    # tty: true
    # stdin_open: true
    # command: /bin/sh

  npm:
    image: node:16-alpine
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./app:/app
      - /app/node_modules
